FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./src ./src
COPY ./logs ./logs
COPY ./data ./data

ENV PYTHONPATH=/app/src

# Default command (can be overridden)
CMD ["python", "-m", "scraper.spider"] 